### PR TITLE
PricingItem - enum destructuring updated

### PR DESCRIPTION
**Pull request by cindRoberta**

### CODE REVIEW

**Comment by Sija** [comment]
@cindRoberta Thanks for your first contribution! It will be much easier if you'd make just a single PR fixing all of the places at once, thanks!

**Comment by cindRoberta** [comment]
> @cindRoberta Thanks for your first contribution! It will be much easier if you'd make just a single PR fixing all of the places at once, thanks!

github has this option? or only git?

**Comment by Sija** [comment]
You'd need to open a fresh PR containg all of the changes.

**Comment by gdotdesign** [comment]
All enum related changes are done under the https://github.com/mint-lang/mint-ui/tree/mint-0.13.0 branch, so I'm closing all these PRs.

**Pull request closed without merging**
